### ISSUE TITLE
Send to Kindle EPUB title issues

### ISSUE THREAD

**Issue by aeorxc** [postlight/parser#715]
Hi

As per:
https://www.fivefilters.org/2022/kindle-epub-issues/

Some recent changes in Amazon's send to kindle service are no longer taking the title from the EPUB metadata. As a result, webpages sent to a kindle appear in the kindle with some kind of random number, eg 1669106941392.

Is it possible to send the EPUB to amazon - renamed with the correct title?

## Expected Behavior

Titles on the kindle should represent the actual title from the webpage.

## Current Behavior

Titles on the kindle appear to be integers.

## Steps to Reproduce

Send any article/webpage to a kindle and check how it appears on the kindle.

## Possible Solution

Rename the file sent from yourselves to Amazon to be renamed with the title.

**Comment by FBoucher** [comment]
It does this with all the articles for me. This was introduced with the change to epub file

**Comment by bobsys** [comment]
I am also seeing this.
When the epub file is opened on Kindle it shows a Table of Contents page and a second page which is the actual book containing the correct title. It seems like there is an unnecessary step of building in a table of contents to the epub file before it is shipped to the Kindle device.

**Comment by gravitacoes** [comment]
No changes on this so far? My uploaded files keep generating an unnecessary index.

**Comment by fboucher** [comment]
it's fixed now. this should be close.

**Comment by bobsys** [comment]
Still has the problems of not assigning the article title and it still shows the table of contents page when viewed on the Kindle device.
